### ISSUE TITLE
Calderon Lab's First Halloween!!🎃👻

### ISSUE THREAD

**Issue by katkinyamaguchi** [diego-calderon-lab/diego-calderon-lab.github.io#3]
![IMG_8717](https://github.com/user-attachments/assets/616177c5-046f-4064-aee3-8885187d1568)
Paper Reviewers 1 (Diego), 2 (Kina), and 3 (Angela). So spooky👻

10/31/2024

**Comment by dcalderon** [comment]
Added this post with [8cc4b3a](https://github.com/diego-calderon-lab/diego-calderon-lab.github.io/commit/8cc4b3a14c130f0d16b154408cd527220cc5b65f). Happy Halloween!!
